
--> 1) How many artists are there 
SELECT COUNT(*)
FROM Artist

--> 2) Dates of successful Tate Modern Exhibitions in descending order
SELECT EXHIBITIONID, EXHIBITIONNAME, STARTDATE, ENDDATE
FROM Exhibition
WHERE STARTDATE <"2018-03-
08"
ORDER BY STARTDATE DESC

--> 3) Inner Joins 
SELECT EXTERNALID, EXTERNALNAME, CITY, COUNTRY, RENTALPRICE, PAINTINGID
FROM ExternalMuseums INNER
JOIN Rental
ON
ExternalMuseums.RENTALID= Rental.RENTALID

--> 4) Right Joins 
SELECT RENTALID, RENTALSTARTDATE, RENTALENDDATE, RENTALPRICE, YEAR, TITLE, ARTISTICSTYLE, ARTISTID
FROM Rental RIGHT JOIN
Painting
ON Rental.PAINTINGID=
Painting.PAINTINGID

--> 5) Left Joins 
SELECT ACQUISITIONDATE, COLLECTIONID, ACQUISITIONCOST, CURRENTDISPLAYSTATUS, TITLE, YEAR
FROM PermanentCollection LEFT JOIN Painting
ON
PermanentCollection.PAINTINGI D= Painting.PAINTINGID
ORDER BY YEAR

-->6) SUM
SELECT MUSEUMID, SUM(ACQUISITIONCOST)
FROM PermanentCollection GROUP BY MUSEUMID

-->7) Rental and Painting Table 
SELECT RENTALID, RENTALSTARTDATE, RENTALENDDATE, RENTALPRICE, CONCAT(PAINTINGID) AS 'LOANED PAINTINGS'
FROM Rental
ORDER BY RENTALID, PAINTINGID

-->8) Permanent Collection
SELECT CURRENTDISPLAYSTATUS, COUNT(COLLECTIONID)
FROM PermanentCollection WHERE ACQUISITIONCOST>100000 GROUP BY CURRENTDISPLAYSTATUS

-->9) Exhibition
SELECT EXHIBITIONNAME, COUNT(EXHIBITIONID)
FROM Exhibition
GROUP BY EXHIBITIONNAME HAVING COUNT(EXHIBITIONID)>0

-->10) Artist Table 
SELECT FULLNAME, BIRTHDATE, DEATHDATE, BIRTHPLACE, ARTISTICEPOCH, OVERVIEW
FROM Artist
WHERE FULLNAME LIKE 'R%'
ORDER BY FULLNAME ASC
