--> SQL Table Creation and Insertion Scripts

CREATE TABLE Artist(
ARTISTID char(6), FULLNAME char(20), BIRTHDATE DATE, BIRTHPLACE char(20), DEATHDATE DATE,
ARTISTICEPOCH VARCHAR(20), PRIMARYSTYLE VARCHAR(20), OVERVIEW VARCHAR(20),
CONSTRAINT pk_Artist_Artistid PRIMARY KEY (ARTISTID)
);

INSERT INTO Artist (ARTISTID, FULLNAME, BIRTHDATE, BIRTHPLACE, DEATHDATE, ARTISTICEPOCH, PRIMARYSTYLE, OVERVIEW) VALUES
('ART001', 'FRIDA KAHLO', "1907-07-06", 'MEXICO', "1954-07-13", 'SURREALISM','MAGICREALISM', 'POLITICAL ARTIST');

INSERT INTO Artist (ARTISTID, FULLNAME, BIRTHDATE, BIRTHPLACE, DEATHDATE, ARTISTICEPOCH, PRIMARYSTYLE, OVERVIEW) VALUES
('ART002', 'VINCENT VAN GOGH', "1853-03-30", 'NETHERLANDS', "1890-07-29", 'POSTIMPRESSIONISM', 'IMPASTO', 'TORTURED ARTIST');

INSERT INTO Artist (ARTISTID, FULLNAME, BIRTHDATE, BIRTHPLACE, DEATHDATE, ARTISTICEPOCH, PRIMARYSTYLE, OVERVIEW) VALUES
('ART003', 'JACKSON POLLOCK', "1912-01-28", 'USA', "1956-08-11", 'ABSTRACT', 'ACTIONPAINTING', 'RECLUSIVE ARTIST');

INSERT INTO Artist (ARTISTID, FULLNAME, BIRTHDATE, BIRTHPLACE, DEATHDATE, ARTISTICEPOCH, PRIMARYSTYLE, OVERVIEW) VALUES
('ART004', 'ANDY WARHOL', "1928-08-06", 'USA', "1987-02-22", 'POPART', 'SCREENPRINTING', 'PAINTED MONROE');

INSERT INTO Artist (ARTISTID, FULLNAME, BIRTHDATE, BIRTHPLACE, DEATHDATE, ARTISTICEPOCH, PRIMARYSTYLE, OVERVIEW) VALUES
('ART005', 'PABLO PICASSO', "1881-10-25", 'SPAIN', "1973-04-08", 'CUBISM', 'SURREALISM', 'INFLUENTIAL ARTIST');

INSERT INTO Artist (ARTISTID, FULLNAME, BIRTHDATE, BIRTHPLACE, DEATHDATE, ARTISTICEPOCH, PRIMARYSTYLE, OVERVIEW) VALUES
('ART006', 'ROY LICHTENSTEIN', "1923-10-27", 'USA', "1997-09-29", 'POPART', 'CONTEMPORARY', 'VITAL IN POP ART');
 
INSERT INTO Artist (ARTISTID, FULLNAME, BIRTHDATE, BIRTHPLACE, DEATHDATE, ARTISTICEPOCH, PRIMARYSTYLE, OVERVIEW) VALUES
('ART007', 'MAX ERNST', "1891-04-02", 'GERMANY', "1976-04-01", 'SURREALISM', 'DADA', 'SURREALISM PIONEER');

INSERT INTO Artist (ARTISTID, FULLNAME, BIRTHDATE, BIRTHPLACE, DEATHDATE, ARTISTICEPOCH, PRIMARYSTYLE, OVERVIEW) VALUES
('ART008', 'CLAUDE MONET', "1840-11-14",'FRANCE', "1926-12-05", 'IMPRESSIONISM', 'IMPRESSIONISM', 'PIVOTAL ARTIST');

INSERT INTO Artist (ARTISTID, FULLNAME, BIRTHDATE, BIRTHPLACE, DEATHDATE, ARTISTICEPOCH, PRIMARYSTYLE, OVERVIEW) VALUES
('ART009', 'SALVADOR DALI', "1904-05-11", 'SPAIN', "1989-01-23", 'CUBISM', 'GRAPHICARTS', 'SKILLED SURREALIST');

INSERT INTO Artist (ARTISTID, FULLNAME, BIRTHDATE, BIRTHPLACE, DEATHDATE, ARTISTICEPOCH, PRIMARYSTYLE, OVERVIEW) VALUES
('ART010', 'PAULINE BOTY', "1938-03-06", 'ENGLAND', "1966-07-01", 'POPART', 'ICONOGRAPHY', 'FEMINIST HERALD');

INSERT INTO Artist(ARTISTID, FULLNAME, BIRTHDATE, BIRTHPLACE, DEATHDATE, ARTISTICEPOCH, PRIMARYSTYLE, OVERVIEW) VALUES
('ART011', 'RICHARD HAMILTON', "1922-02-24", 'ENGLAND', "2011-09-13", 'POPART', 'CONTEMPORARY', 'INFLUENTIAL ARTIST');

INSERT INTO Artist(ARTISTID, FULLNAME, BIRTHDATE, BIRTHPLACE, DEATHDATE, ARTISTICEPOCH, PRIMARYSTYLE, OVERVIEW) VALUES
('ART012', 'CAMILLE PISSARRO', "1830-07-10", 'DANISH WEST INDIES', "1903-11-13", 'IMPRESSIONISM', 'POINTILLISM', 'EARLY IMPRESSIONIST');

INSERT INTO Artist(ARTISTID, FULLNAME, BIRTHDATE, BIRTHPLACE, DEATHDATE,
 
ARTISTICEPOCH, PRIMARYSTYLE, OVERVIEW) VALUES
('ART013', 'BERTHE MORISOT', "1841-01-14", 'FRANCE', "1895-03-02", 'IMPRESSIONISM', 'IMPRESSIONISM', 'FEMALE IMPRESSIONIST');

INSERT INTO Artist(ARTISTID, FULLNAME, BIRTHDATE, BIRTHPLACE, DEATHDATE, ARTISTICEPOCH, PRIMARYSTYLE, OVERVIEW) VALUES
('ART014', 'RENE MAGRITTE', "1898-11-21", 'BELGIUM', "1967-08-15", 'SURREALISM', 'DADA', 'BELGIAN SURREALIST');

INSERT INTO Artist(ARTISTID, FULLNAME, BIRTHDATE, BIRTHPLACE, DEATHDATE, ARTISTICEPOCH, PRIMARYSTYLE, OVERVIEW) VALUES
('ART015', 'EVELYNE AXELL', "1935-08-16", 'BELGIUM', "1972-09-10", 'POPART', 'CONTEMPORARY', 'FEMINIST ARTIST');


CREATE TABLE Museum (
MUSEUMID char(6), MUSEUMNAME char(20),
 
PHONENUMBER VARCHAR(15), ADDRESS VARCHAR(30),
CITY char(20), COUNTRY char(20),
POSTCODE VARCHAR(8),
CONSTRAINT pk_Museum_Museumid PRIMARY KEY (MUSEUMID)
);

INSERT INTO Museum (MUSEUMID, MUSEUMNAME, PHONENUMBER, ADDRESS,CITY, COUNTRY, POSTCODE) VALUES
('MUS001', 'TATE MODERN', '020 7887 8888', 'Bankside', 'LONDON', 'ENGLAND', 'SE1 9TG');

CREATE TABLE Painting ( PAINTINGID char(6), YEAR INT(4),
TITLE VARCHAR(60), DESCRIPTION VARCHAR(60), PAINTTYPE VARCHAR(30), MATERIAL VARCHAR(20), ARTISTICSTYLE VARCHAR(50),
 
ARTISTID char(6));


Alter table Painting ADD CONSTRAINT pk_Painting_Paintingid PRIMARY KEY (PAINTINGID);
Alter table Painting add CONSTRAINT fk_Painting_Artistid FOREIGN KEY (ARTISTID) REFERENCES Artist (ARTISTID);


INSERT INTO Painting (PAINTINGID, YEAR, TITLE,
DESCRIPTION, PAINTTYPE, MATERIAL, ARTISTICSTYLE, ARTISTID) VALUES ('PAI001', 1932, 'HENRY FORD HOSPITAL',
'KAHLO LYING ON BED', 'OIL', 'WOOD', 'MAGICREALISM', 'ART001');



INSERT INTO Painting (PAINTINGID, YEAR, TITLE,
DESCRIPTION, PAINTTYPE, MATERIAL, ARTISTICSTYLE, ARTISTID) VALUES ('PAI002', 1889, 'THE STARRY NIGHT',
'VIEW FROM HIS ASYLUM ROOM', 'OIL', 'CANVAS', 'IMPASTO', 'ART002');





INSERT INTO Painting (PAINTINGID, YEAR, TITLE,
DESCRIPTION, PAINTTYPE, MATERIAL, ARTISTICSTYLE, ARTISTID) VALUES ('PAI003', 1952, 'CONVERGENCE',
'REBELLIOUS ART AGAINST OPPRESSION', 'OIL', 'CANVAS', 'ACTIONPAINTING', 'ART003');



INSERT INTO Painting (PAINTINGID, YEAR, TITLE,
DESCRIPTION, PAINTTYPE, MATERIAL, ARTISTICSTYLE, ARTISTID) VALUES ('PAI004', 1962, 'MARILYN DIPTYCH',
 
'ART OF MONROE', 'WATERCOLOURS', 'CANVAS', 'SCREENPRINTING', 'ART004');



INSERT INTO Painting (PAINTINGID, YEAR, TITLE,
DESCRIPTION, PAINTTYPE, MATERIAL, ARTISTICSTYLE, ARTISTID) VALUES ('PAI005', 1937, 'GUERNICA',
'POWERFUL ART AGAINST THE SPANISH CIVIL WAR', 'OIL', 'CANVAS', 'CUBISM', 'ART005');



INSERT INTO Painting (PAINTINGID, YEAR, TITLE,
DESCRIPTION, PAINTTYPE, MATERIAL, ARTISTICSTYLE, ARTISTID) VALUES ('PAI006', 1963, 'IN THE CAR',
'REPRESENTS ESSENCE OF TIME', 'WATERCOLOURS', 'CANVAS', 'CONTEMPORARY', 'ART006');



INSERT INTO Painting (PAINTINGID, YEAR, TITLE,
DESCRIPTION, PAINTTYPE, MATERIAL, ARTISTICSTYLE, ARTISTID) VALUES ('PAI007', 1941, 'NAPOLEON IN THE WILDERNESS',
'FOREGROUND PORTRAYS ERNSTS PARTNER', 'OIL', 'CANVAS', 'SURREALISM', 'ART007');



INSERT INTO Painting (PAINTINGID, YEAR, TITLE,
DESCRIPTION, PAINTTYPE, MATERIAL, ARTISTICSTYLE, ARTISTID) VALUES ('PAI008', 1872, 'IMPRESSION SUNRISE',
'PORT OF MONETS LE HAVRE HOMETOWN', 'OIL', 'CANVAS', 'IMPRESSIONISM', 'ART008');
 

INSERT INTO Painting (PAINTINGID, YEAR, TITLE,
DESCRIPTION, PAINTTYPE, MATERIAL, ARTISTICSTYLE, ARTISTID) VALUES ('PAI009', 1931, 'THE PERSISTENCE OF MEMORY',
'ART OF FANTASY', 'OIL', 'CANVAS', 'SURREALISM', 'ART009');



INSERT INTO Painting (PAINTINGID, YEAR, TITLE,
DESCRIPTION, PAINTTYPE, MATERIAL, ARTISTICSTYLE, ARTISTID) VALUES ('PAI010', 1964, 'COUNTDOWN TO VIOLENCE',
'THE ART OF FEMINISM', 'OIL', 'CANVAS', 'FEMINIST ART', 'ART010');



INSERT INTO Painting (PAINTINGID, YEAR, TITLE,
DESCRIPTION, PAINTTYPE, MATERIAL, ARTISTICSTYLE, ARTISTID) VALUES ('PAI011', '1984', 'LOBBY', 'METAPHOR FOR PURGATORY', 'WATERCOLOURS', 'PAPER', 'SCREENPRINTING', 'ART011');

INSERT INTO Painting (PAINTINGID, YEAR, TITLE,
DESCRIPTION, PAINTTYPE, MATERIAL, ARTISTICSTYLE, ARTISTID) VALUES ('PAI012', '1871', 'THE CRYSTAL PALACE', 'VISUAL OF HIS VISIT TO ENGLAND', 'OIL', 'CANVAS', 'IMPRESSIONISM', 'ART012');

INSERT INTO Painting (PAINTINGID, YEAR, TITLE,
DESCRIPTION, PAINTTYPE, MATERIAL, ARTISTICSTYLE, ARTISTID) VALUES ('PAI013', 1872, 'THE CRADLE', 'IMAGE OF MOTHERHOOD',
'OIL', 'CANVAS', 'IMPRESSIONISM', 'ART013');


INSERT INTO Painting (PAINTINGID, YEAR, TITLE,
 
DESCRIPTION, PAINTTYPE, MATERIAL, ARTISTICSTYLE, ARTISTID) VALUES
('PAI014', 1929, 'THE TREACHERY OF IMAGES', 'GAP BETWEEN LANGUAGE AND MEANING', 'OIL', 'CANVAS', 'SURREALISM', 'ART014');



INSERT INTO Painting (PAINTINGID, YEAR, TITLE,
DESCRIPTION, PAINTTYPE, MATERIAL, ARTISTICSTYLE, ARTISTID) VALUES ('PAI015', 1964, 'ICE CREAM', 'PROGRESSIVE AND EXPLICIT PIECE OF ART', 'OIL', 'CANVAS', 'CONTEMPORARY', 'ART015');

CREATE TABLE Exhibition ( EXHIBITIONID char(6), EXHIBITIONNAME VARCHAR(90), STARTDATE DATE,
ENDDATE DATE, COUNTRY char(40),
CITY char (40),
 
PAINTINGID char(6), MUSEUMID char(6));



Alter table Exhibition add constraint pk_exhibition_exhibitionid primary key (EXHIBITIONID);


Alter table Exhibition add constraint fk_exhibition_paintingid foreign key (Paintingid) REFERENCES Painting (Paintingid);


Alter table Exhibition add constraint fk_exhibition_museumid foreign key (museumid) REFERENCES Museum (museumid);


INSERT INTO Exhibition (EXHIBITIONID, EXHIBITIONNAME, STARTDATE, ENDDATE, COUNTRY, CITY, PAINTINGID, MUSEUMID) VALUES ('MOM098', 'TATE MODERN CAPTURING THE MOMENT', "2023-06-13", "2024-04-28", 'ENGLAND', 'LONDON', 'PAI010', 'MUS001');

INSERT INTO Exhibition (EXHIBITIONID, EXHIBITIONNAME, STARTDATE, ENDDATE, COUNTRY, CITY, PAINTINGID, MUSEUMID) VALUES ('INT367', 'TATE MODERN THE WORLD GOES POP', "2015-09-17", "2016-01-24",'ENGLAND', 'LONDON','PAI006', 'MUS001');



INSERT INTO Exhibition (EXHIBITIONID, EXHIBITIONNAME, STARTDATE, ENDDATE, COUNTRY, CITY, PAINTINGID, MUSEUMID) VALUES
('SUR001', 'TATE MODERN SURREALISM BEYOND BORDERS', "2022-02-24", "2022-08-29", 'ENGLAND', 'LONDON', 'PAI007', 'MUS001');

INSERT INTO Exhibition (EXHIBITIONID, EXHIBITIONNAME, STARTDATE, ENDDATE, COUNTRY, CITY, PAINTINGID, MUSEUMID) VALUES ('VAN002', 'TATE MODERN VAN GOGH AND BRITAIN', "2019-03-27", "2019-08-11", 'ENGLAND', 'LONDON', 'PAI002','MUS001');
 

INSERT INTO Exhibition (EXHIBITIONID, EXHIBITIONNAME, STARTDATE, ENDDATE, COUNTRY, CITY, PAINTINGID, MUSEUMID) VALUES
('IMP018', 'TATE MODERN THE IMPRESSIONISTS IN LONDON', "2017-11-02", "2018-05-07", 'ENGLAND', 'LONDON', 'PAI008', 'MUS001');

INSERT INTO Exhibition (EXHIBITIONID, EXHIBITIONNAME, STARTDATE, ENDDATE, COUNTRY, CITY, PAINTINGID, MUSEUMID) VALUES ('WAR928', 'TATE MODERN ANDY WARHOL', "2020-03-12",
"2020-11-15", 'ENGLAND', 'LONDON', 'PAI004', 'MUS001');


INSERT INTO Exhibition (EXHIBITIONID, EXHIBITIONNAME, STARTDATE, ENDDATE, COUNTRY, CITY, PAINTINGID, MUSEUMID) VALUES ('EXH001', 'TATE MODERN EXPRESSIONISTS', "2024-04-25",
"2024-10-20", 'ENGLAND', 'LONDON', 'PAI003', 'MUS001');


INSERT INTO Exhibition (EXHIBITIONID, EXHIBITIONNAME, STARTDATE, ENDDATE, COUNTRY, CITY, PAINTINGID, MUSEUMID) VALUES
('PIC932', 'TATE MODERN PICASSO', "2018-03-08",
"2018-09-09", 'ENGLAND', 'LONDON', 'PAI005', 'MUS001');


INSERT INTO Exhibition (EXHIBITIONID, EXHIBITIONNAME, STARTDATE, ENDDATE, COUNTRY, CITY, PAINTINGID, MUSEUMID) VALUES ('DAL007', 'DALI AT TATE MODERN', "2007-06-01",
"2007-09-09", 'ENGLAND', 'LONDON', 'PAI009', 'MUS001');




INSERT INTO Exhibition (EXHIBITIONID, EXHIBITIONNAME, STARTDATE, ENDDATE, COUNTRY, CITY, PAINTINGID, MUSEUMID) VALUES ('KAH005', 'TATE MODERN FRIDA KAHLO', "2005-05-01",
"2005-10-07", 'ENGLAND', 'LONDON', 'PAI001', 'MUS001')
 

INSERT INTO Exhibition (EXHIBITIONID, EXHIBITIONNAME, STARTDATE, ENDDATE, COUNTRY, CITY, PAINTINGID, MUSEUMID) VALUES ('POP899', 'TATE MODERN THE WORLD GOES POP', "2015-09-17", "2016-01-24",'ENGLAND', 'LONDON','PAI011', 'MUS001');

INSERT INTO Exhibition (EXHIBITIONID, EXHIBITIONNAME, STARTDATE, ENDDATE, COUNTRY, CITY, PAINTINGID, MUSEUMID) VALUES
('IMP001', 'TATE MODERN THE IMPRESSIONISTS IN LONDON', "2017-11-02", "2018-05-07", 'ENGLAND', 'LONDON', 'PAI012', 'MUS001');

INSERT INTO Exhibition (EXHIBITIONID, EXHIBITIONNAME, STARTDATE, ENDDATE, COUNTRY, CITY, PAINTINGID, MUSEUMID) VALUES
('IMP008', 'TATE MODERN THE IMPRESSIONISTS IN LONDON', "2017-11-02", "2018-05-07", 'ENGLAND', 'LONDON', 'PAI013', 'MUS001');

INSERT INTO Exhibition (EXHIBITIONID, EXHIBITIONNAME, STARTDATE, ENDDATE, COUNTRY, CITY, PAINTINGID, MUSEUMID) VALUES
('SUR002', 'TATE MODERN SURREALISM BEYOND BORDERS', "2022-02-24", "2022-08-29", 'ENGLAND', 'LONDON', 'PAI014', 'MUS001');

INSERT INTO Exhibition (EXHIBITIONID, EXHIBITIONNAME, STARTDATE, ENDDATE, COUNTRY, CITY, PAINTINGID, MUSEUMID) VALUES ('DMOM09', 'TATE MODERN CAPTURING THE MOMENT', "2023-06-13", "2024-04-28", 'ENGLAND', 'LONDON', 'PAI015', 'MUS001');

CREATE TABLE Rental ( RENTALID char(6), RENTALSTARTDATE DATE, RENTALENDDATE DATE, RENTALPRICE INT(5), PAINTINGID char(6));



Alter table Rental add CONSTRAINT pk_Rental_Rentalid PRIMARY KEY (RENTALID);
Alter table Rental add CONSTRAINT fk_Rental_Paintingid FOREIGN KEY (PAINTINGID) REFERENCES Painting (PAINTINGID);







INSERT INTO Rental (RENTALID, RENTALSTARTDATE, RENTALENDDATE, RENTALPRICE, PAINTINGID) VALUES
('REN001', "2024-01-10", "2024-10-27", "355000", 'PAI003');
 
INSERT INTO Rental (RENTALID, RENTALSTARTDATE, RENTALENDDATE, RENTALPRICE, PAINTINGID) VALUES
('REN002', "2023-02-14", "2024-05-05", 500000,'PAI010');




INSERT INTO Rental (RENTALID, RENTALSTARTDATE, RENTALENDDATE, RENTALPRICE, PAINTINGID) VALUES
('REN003', "2021-11-13", "2022-09-10", '955000','PAI007'),
('REN004', "2017-05-08", "2018-05-15", '450000', 'PAI008'),
('REN005', "2007-01-15", "2007-09-16", '700000', 'PAI009');


INSERT INTO Rental (RENTALID, RENTALSTARTDATE, RENTALENDDATE, RENTALPRICE, PAINTINGID) VALUES
('REN006', "2017-03-01", "2018-05-22", 400000, 'PAI012');


INSERT INTO Rental (RENTALID, RENTALSTARTDATE, RENTALENDDATE, RENTALPRICE, PAINTINGID) VALUES
('REN007', "2021-10-08", "2022-09-24", 989000, 'PAI014');

CREATE TABLE ExternalMuseums (EXTERNALID char(6), EXTERNALNAME VARCHAR (60), PHONENUMBER VARCHAR(15), ADDRESS VARCHAR(30),
CITY char (40), COUNTRY char(40),
POSTCODE VARCHAR(15), RENTALID char(6), MUSEUMID char(6));



Alter table ExternalMuseums add constraint pk_ExternalMuseums_Externalid primary key (EXTERNALID);
Alter table ExternalMuseums add constraint fk_ExternalMuseums_Rentalid foreign key (RENTALID) References Rental (RENTALID);
Alter table ExternalMuseums add constraint fk_ExternalMuseums_museumid foreign key (museumid) REFERENCES Museum (museumid);





INSERT INTO ExternalMuseums (EXTERNALID, EXTERNALNAME, PHONENUMBER, ADDRESS, CITY, COUNTRY, POSTCODE, RENTALID, MUSEUMID) VALUES
('EXT001', 'THE NATIONAL GALLERY OF ART', '+1 202-737-4215',
'CONSTITUTION AVE NW', 'WASHINGTON DC', 'USA', '20565', 'REN001', 'MUS001');


INSERT INTO ExternalMuseums (EXTERNALID, EXTERNALNAME, PHONENUMBER, ADDRESS, CITY, COUNTRY, POSTCODE, RENTALID, MUSEUMID) VALUES
('EXT002', 'THE LOUVRE', '+33 40 20 53 17',
'PARIS', 'PARIS', 'FRANCE', '75001', 'REN002', 'MUS001');
 
INSERT INTO ExternalMuseums (EXTERNALID, EXTERNALNAME, PHONENUMBER, ADDRESS, CITY, COUNTRY, POSTCODE, RENTALID, MUSEUMID) VALUES
('EXT003', 'THE NATIONAL GALLERY', '020 7747 2885',
'TRAFALGAR SQUARE', 'LONDON', 'ENGLAND', 'WC2N 5DN', 'REN003', 'MUS001');


INSERT INTO ExternalMuseums (EXTERNALID, EXTERNALNAME, PHONENUMBER, ADDRESS, CITY, COUNTRY, POSTCODE, RENTALID, MUSEUMID) VALUES
('EXT004', 'THE UFFIZI GALLERY', '+39 055 294883',
'FLORENCE', 'METROPOLITAN CITY OF FLORENCE', 'ITALY', '50122', 'REN004', 'MUS001');


INSERT INTO ExternalMuseums (EXTERNALID, EXTERNALNAME, PHONENUMBER, ADDRESS, CITY, COUNTRY, POSTCODE, RENTALID, MUSEUMID) VALUES
('EXT005', 'DALI THEATRE AND MUSEUM', '+34 67 75 00', 'FIGUERES', 'GIRONA', 'SPAIN', '17600', 'REN005', 'MUS001');

INSERT INTO ExternalMuseums (EXTERNALID, EXTERNALNAME, PHONENUMBER, ADDRESS, CITY, COUNTRY, POSTCODE, RENTALID, MUSEUMID) VALUES
('EXT006', 'ART INSTITUTE OF CHICAGO', '(312) 629-9420', 'Michigan Ave', 'CHICAGO', 'USA', 'IL 60603', 'REN006', 'MUS001');

INSERT INTO ExternalMuseums (EXTERNALID, EXTERNALNAME, PHONENUMBER, ADDRESS, CITY, COUNTRY, POSTCODE, RENTALID, MUSEUMID) VALUES
('EXT007', 'The Los Angeles County Museum of Art', '+1 323-857-6000', 'Wilshire Blvd', 'LOS ANGELES', 'USA', '90036', 'REN007', 'MUS001');

CREATE TABLE PermanentCollection( COLLECTIONID char(6), ACQUISITIONDATE DATE, CURRENTDISPLAYSTATUS VARCHAR(50), ACQUISITIONCOST INT(6),
PAINTINGID char(6), MUSEUMID char(6),
CONSTRAINT pk_PermanentCollection_Collectionid PRIMARY KEY (COLLECTIONID),
CONSTRAINT fk_PermanentCollection_Paintingid FOREIGN KEY (PAINTINGID) REFERENCES Painting (PAINTINGID),
CONSTRAINT fk_PermanentCollection_Museumid FOREIGN KEY (MUSEUMID) REFERENCES Museum (MUSEUMID)

);

INSERT INTO PermanentCollection (COLLECTIONID, ACQUISITIONDATE, CURRENTDISPLAYSTATUS, ACQUISITIONCOST,
PAINTINGID, MUSEUMID) VALUES
('PE001', "2019-12-01", 'EXHIBITED', 955000, 'PAI004', 'MUS001');

INSERT INTO PermanentCollection (COLLECTIONID, ACQUISITIONDATE, CURRENTDISPLAYSTATUS, ACQUISITIONCOST,
PAINTINGID, MUSEUMID) VALUES
('PE002', '2018-12-27', 'IN STORAGE', 100000, 'PAI002', 'MUS001');
 
INSERT INTO PermanentCollection (COLLECTIONID, ACQUISITIONDATE, CURRENTDISPLAYSTATUS, ACQUISITIONCOST,
PAINTINGID, MUSEUMID) VALUES
('PE003', '2015-01-09', 'EXHIBITED', 300000, 'PAI006', 'MUS001');

INSERT INTO PermanentCollection (COLLECTIONID, ACQUISITIONDATE, CURRENTDISPLAYSTATUS, ACQUISITIONCOST,
PAINTINGID, MUSEUMID) VALUES
('PE004', '2005-01-25', 'EXHIBITED', 780000, 'PAI001', 'MUS001');

INSERT INTO PermanentCollection (COLLECTIONID, ACQUISITIONDATE, CURRENTDISPLAYSTATUS, ACQUISITIONCOST,
PAINTINGID, MUSEUMID) VALUES
('PE005', '2018-01-20', 'IN STORAGE', 150000, 'PAI005', 'MUS001');

INSERT INTO PermanentCollection (COLLECTIONID, ACQUISITIONDATE, CURRENTDISPLAYSTATUS, ACQUISITIONCOST,
PAINTINGID, MUSEUMID) VALUES
('PE006', '2015-01-01', 'IN STORAGE', 200000, 'PAI011', 'MUS001');

INSERT INTO PermanentCollection (COLLECTIONID, ACQUISITIONDATE, CURRENTDISPLAYSTATUS, ACQUISITIONCOST,
PAINTINGID, MUSEUMID) VALUES
('PE007', "2017-02-14", 'EXHIBITED', 255000, 'PAI013', 'MUS001');

INSERT INTO PermanentCollection (COLLECTIONID, ACQUISITIONDATE, CURRENTDISPLAYSTATUS, ACQUISITIONCOST,
 PAINTINGID, MUSEUMID) VALUES
('PE008', "2023-01-13", 'EXHIBITED', 700000, 'PAI015', 'MUS001');
